app = "execpartners-sim"
primary_region = "fra"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.ports]]
    port = 80
  [[http_service.ports]]
    port = 443

  [[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "15s"
    method = "GET"
    path = "/"
